# Generated by Django 2.1.3 on 2018-11-17 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20181117_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinstance',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='eventinstance',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Place'),
        ),
        migrations.AlterField(
            model_name='eventinstance',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
