# Generated by Django 2.1.3 on 2018-11-17 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_auto_20181117_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinstance',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Place'),
        ),
        migrations.AlterField(
            model_name='place',
            name='price_quartile',
            field=models.CharField(choices=[('1', '$'), ('2', '$$'), ('3', '$$$'), ('4', '$$$$')], max_length=1),
        ),
    ]
