# Generated by Django 2.1.3 on 2018-11-27 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_auto_20181126_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinstance',
            name='place',
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.Place'),
        ),
    ]
