# Generated by Django 2.1.3 on 2018-12-06 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_auto_20181201_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='cuisine',
            field=models.CharField(choices=[('1', 'American'), ('2', 'Italian'), ('3', 'Steakhouse'), ('4', 'Seafood'), ('5', 'French'), ('6', 'Indian'), ('7', 'Mexican'), ('8', 'Japanese'), ('9', 'British'), ('10', 'Chinese'), ('11', 'Spanish'), ('12', 'Fusion/Eclectic'), ('13', 'Barbecue'), ('14', 'Greek'), ('15', 'Tapas/Small Plates'), ('16', 'Comfort Food'), ('17', 'Burgers'), ('18', 'Vegiterian/Vegan'), ('19', 'Fish'), ('20', 'Dessert'), ('21', 'Burmese'), ('22', 'Asian'), ('23', 'Bar/Lounge/Bottle Service'), ('24', 'Beer Garden'), ('25', 'Bistro'), ('26', 'Cajun'), ('27', 'Californian'), ('28', 'Cocktail Bar'), ('29', 'Creole'), ('30', 'Gastro Pub'), ('31', 'Global/International'), ('32', 'Latin/Spanish'), ('33', 'Latin American'), ('34', 'Mediterranean'), ('35', 'Peruvian'), ('36', 'Southwest'), ('37', 'Tex-Mex'), ('38', 'Wine Bar'), ('39', 'Farm-to-Table')], default=4, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.Place'),
        ),
    ]
