# Generated by Django 2.1.3 on 2018-12-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_auto_20181209_1239'),
        ('scheduler', '0015_auto_20181206_1904'),
    ]

    operations = [
    ]
