# Generated by Django 2.1.3 on 2018-12-26 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0021_auto_20181226_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='owner',
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.Place'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
