# Generated by Django 2.1.3 on 2018-12-27 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0027_auto_20181227_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='date',
            field=models.DateField(default='2018-12-26', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='time',
            field=models.TimeField(default='17:00', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.Place'),
        ),
    ]
